PSM-1474 ErrorProne bugpattern for removing duplicate `expectNext` calls
PicnicSupermarket/error-prone-support pull request #443
Opened 2023-01-04 23:58 UTC by SimonBaars

Woowee! That was a freaking mess.

At first I thought I could easily solve this with a little Refaster pattern. Boy was I wrong. So many edge cases, some many little thingies. So I went down the Error Prone rabbit hole, and boi was it deep. Who knew simply traversing nodes in an AST could be such a mess? Hell, even internal functions of Error Prone (yes I'm talking about you `ASTHelpers.findEnclosingNode`) have infinite while loops in them. BWAAAAH!

Anyway, it's 1AM in the night and I think I have a fully working version. As in, I made all the tests I could think of and they pass. Now it's up to the Lvl. 200 mafia bosses @rickie and crew to poke some holes in this dumpster fire of a bugpattern.

To explain a little bit what is going on:
I do a little for-loop where I step to all the other method invocations. The smart logic here is `getChild()`, which jumps `n` steps over the next few nodes (child nodes) to find the next `expectNext` call. By jumping 2 steps at a time, we visit all the method calls. Other types of nodes that it may visit should be eliminated either by the matcher or by the position check.

Also I miss you 😢😢😢😢😢😢❤️

2023-01-04 23:58 UTC, SimonBaars commented
Sometimes it helps to visually review the PR, so here's a little illustration of this PR's contents:
![image](https://user-images.githubusercontent.com/8466614/210672182-4bddf0ad-270a-44cf-8bcf-438ee635aca9.png)

2023-01-05 04:39 UTC, Stephan202 commented
Nice parting gift @SimonBaars! :smile:

W.r.t. the build failures: Running `./apply-error-prone-suggestions.sh` (with #441) should (largely) take care of those. :sparkles:

Shame that the various `expectNext` overloads aren't supported by Refaster's `@Repeated` annotation; we have a similar issue for `ImmutableList.of` and friends. Thinking of all the combinations that'd be necessary, I agree that a `BugChecker` is indeed the way to go.

I'll let Lvl. boss @rickie do the first review. :rofl:

2023-01-05 12:38 UTC, rickie commented
Nice job @SimonBaars! It was fun to pair up on this a few times! (Still sad to see you go man 😢) 

Currently review backlog is a bit full, so it'll probably be next week before I can do a proper deep-dive 😉.

2023-01-05 14:19 UTC, SimonBaars commented
> Currently review backlog is a bit full, so it'll probably be next week before I can do a proper deep-dive wink.

You're beginning to turn into a manager!

2023-01-11 21:17 UTC, SimonBaars commented
@rickie 
![image](https://user-images.githubusercontent.com/8466614/211919586-116a5020-5b79-4003-bca9-4d47a8b5499c.png)

2023-01-12 09:04 UTC, rickie requested changes
Nice meme haha, I did an initial review where I first skimmed over the whole setup and provided feedback. Sorry for not getting back earlier to this. The Error Prone Support review backlog is quite big 😅. 

Couldn't apply all feedback myself so leaving some open points for you as well 😉. Hope you don't mind :). 

There are some interesting concepts in this check! Cool stuff!

2023-01-12 09:04 UTC, rickie commented on error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StepVerifierDuplicateExpectNext.java
> +    SuggestedFix.Builder argumentsFix =
`matchMethodInvocation` method is maybe a bit too full. Already made a comment about the middle part. Maybe we can extract the `Description` related things to a method like we do in some other places. Look for the regex: `try.*\(` to see some methods that return either a `Fix` or `Description` for some examples.

2023-01-20 19:44 UTC, SimonBaars commented
@rickie Hey, sorry, I'm not following this thread very actively.
What would you still like me to take a look at?

2023-01-21 11:05 UTC, rickie commented
There are some open points that I haven't addressed yet. If you want, you can take a look there 😄.

2024-01-23 04:39 UTC, closed without merging